[[redirects]]
  from = "/tenis-meia"
  to = "/tenis"
  status = 301

[[redirects]]
  from = "/comprar-tenis-meia"
  to = "https://vt.tiktok.com/ZS9BGBRESdvat-lgr7p/"
  status = 302

[[redirects]]
  from = "/comprar-kit-blusas"
  to = "https://vt.tiktok.com/ZS9BGcRYwuLe4-r4EzT/"
  status = 302

[[redirects]]
  from = "/comprar-creme-ganache"
  to = "https://vt.tiktok.com/ZS9BGKwgB4EbD-ZtHy9/"
  status = 302
